// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      return Hand.__super__.constructor.apply(this, arguments);
    }

    Hand.prototype.model = Card;

    Hand.prototype.canPlay = true;

    Hand.prototype.initialize = function(array, deck, isDealer, points) {
      this.deck = deck;
      this.isDealer = isDealer;
      this.points = points;
    };

    Hand.prototype.hit = function() {
      return this.add(this.deck.pop()).last();
    };

    Hand.prototype.stand = function() {
      this.at(0).flip();
      while (this.scores()[0] < 17) {
        this.hit();
      }
      return this.trigger('compareScore');
    };

    Hand.prototype.scores = function() {
      var hasAce, score;
      hasAce = this.reduce(function(memo, card) {
        return memo || card.get('value') === 1;
      }, false);
      score = this.reduce(function(score, card) {
        return score + (card.get('revealed') ? card.get('value') : 0);
      }, 0);
      if (score > 21 && this.canPlay) {
        this.canPlay = false;
        this.trigger('bust');
      }
      if (score === 21 && this.length === 2 && this.canPlay) {
        this.canPlay = false;
        this.trigger('blackjack');
      }
      if (hasAce) {
        return [score, score + 10];
      } else {
        return [score];
      }
    };

    Hand.prototype.start = function() {
      return this.trigger('startnow');
    };

    return Hand;

  })(Backbone.Collection);

}).call(this);
